# Title: lampaman4ik
#
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via GitHub
#
# Date: 19 November 2024 21:35:37 (UTC)
# Number of unique domains: 121,628
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/LampaMan/lampa-pihole/refs/heads/main/ua
# Project home page: https://github.com/LampaMan/lampa-pihole/refs/heads/main/ua
# 
#
# ===============================================================

127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

# ===============================================================

0.0.0.0 s.schulist.link
0.0.0.0 cpm.smoads.com
0.0.0.0 srv224.com
0.0.0.0 

#   /googlesyndication/
0.0.0.0 googlesyndication.com
0.0.0.0 tpc.googlesyndication.com
0.0.0.0 pagead2.googlesyndication.com
0.0.0.0 ade.googlesyndication.com

#   /google/
0.0.0.0 googleadservices.com
0.0.0.0 fonts.googleapis.com
0.0.0.0 

#   /реклама youtube/
0.0.0.0 googlevideo.com
0.0.0.0 r1---sn-3tp8nu5g-vqne.googlevideo.com
0.0.0.0	r1---sn-3tp8nu5g-v1iz.googlevideo.com
0.0.0.0 rr1---sn-3tp8nu5g-ig3z.googlevideo.com
0.0.0.0 
0.0.0.0 
0.0.0.0 r2---sn-3tp8nu5g-v1iz.googlevideo.com
0.0.0.0 rr2---sn-3tp8nu5g-ig3z.googlevideo.com
0.0.0.0 rr2---sn-3tp8nu5g-3c26.googlevideo.com
0.0.0.0 
0.0.0.0 
0.0.0.0 rr3---sn-3tp8nu5g-ig3z.googlevideo.com
0.0.0.0	rr3---sn-3tp8nu5g-3c2l.googlevideo.com
0.0.0.0	rr3---sn-3tp8nu5g-3c26.googlevideo.com
0.0.0.0 
0.0.0.0 
0.0.0.0 rr4---sn-3tp8nu5g-ig3z.googlevideo.com
0.0.0.0 rr4---sn-3tp8nu5g-3c2e7.googlevideo.com
0.0.0.0 
0.0.0.0 
0.0.0.0 rr5---sn-3tp8nu5g-ig3z.googlevideo.com
0.0.0.0 rr5---sn-3tp8nu5g-3c2d.googlevideo.com
0.0.0.0 
0.0.0.0 
0.0.0.0 rr6---sn-3tp8nu5g-3c2e.googlevideo.com
0.0.0.0 rr6---sn-3tp8nu5g-3c2ee.googlevideo.com
0.0.0.0 
0.0.0.0 

#   /можливо реклама youtube/
0.0.0.0 jnn-pa.googleapis.com
0.0.0.0 yt3.ggpht.com

#   /doubleclick.net/
0.0.0.0 adclick.g.doubleclick.net
0.0.0.0 googleads.g.doubleclick.net
0.0.0.0 doubleclick.net
0.0.0.0 g.doubleclick.net
0.0.0.0 
0.0.0.0 
0.0.0.0 
0.0.0.0 
